//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por intento 2.rc
//
#define IDR_MENU1                       101
#define IDD_REGISTROPAQUETE             102
#define IDD_REGISTROMECANICOS           104
#define IDD_LOGIN                       106
#define IDD_CITAS                       110
#define IDD_CLIENTES                    111
#define IDD_CITASXMECANICO              112
#define IDD_CITASXSEMANA                113
#define IDD_CITASXPAQUETE               114
#define IDD_SALIR                       122
#define IDD_VENPRIN                     124
#define IDD_REPORTECITAS                128
#define IDD_REPORTECLIENTES             130
#define IDD_REPORTEMECANICOS            132
#define IDD_DIALOG1                     134
#define IDD_CITASXNUMERO                134
#define IDC_USUARIOLOGIN                1002
#define IDC_CONTRASENALOGIN             1003
#define BTN_LOGIN                       1004
#define IDC_NOMBRE                      1011
#define COMBO_ESPECIALIDAD              1012
#define CELULAR_MECANICO                1013
#define TURNO_TRABAJO                   1015
#define NUMERO_EMPLEADO                 1016
#define IMAGEN_MECANICO                 1017
#define DIAS_SEMANA_TRABAJO             1018
#define IDC_NOMBRECLIENTE               1019
#define IDC_TELEFONOCLIENTE             1020
#define IDC_DIRECCIONCLIENTE            1021
#define IDC_PLACAVEHICULO               1022
#define IDC_MARCAVEHICULO               1024
#define IDC_MODELOVEHICULO              1025
#define IDC_ANIOVEHICULO                1026
#define BTN_FOTO                        1027
#define IDC_NOMMECANICO                 1028
#define IDC_NOMPAQ                      1029
#define IDC_CLAVEPROD                   1030
#define IDC_PRECIO                      1031
#define CB_LUNES                        1038
#define CB_MARTES                       1039
#define CB_MIERCOLES                    1040
#define CB_JUEVES                       1041
#define CB_VIERNES                      1042
#define CB_SABADO                       1043
#define IDC_NOMBREUS                    1044
#define BTN_SI                          1046
#define BTN_NO                          1047
#define IDC_NOMU                        1048
#define IDC_NOMUS                       1049
#define IDC_NOMUSU                      1050
#define IDC_NOMUSUR                     1051
#define IDC_NOMUSURU                    1052
#define IDC_NOMUSURI                    1053
#define IDC_DESCRIPCION                 1054
#define BM_AUTOCAR                      1055
#define IDC_NOMUSURIO                   1056
#define IDC_KMVEHICULO                  1058
#define IDC_LBCLIENTES                  1059
#define IDC_BTNREGISTRARCITA            1060
#define IDC_CBESPECIALIDAD              1061
#define IDC_NOMUSURIA                   1062
#define IDC_LBMODCLIENTE                1063
#define IDC_BTNDELETECLIENTE            1064
#define IDC_BTNMODCLIENTE               1065
#define IDC_LBMODMECANICO               1066
#define IDC_BTNMODMECANICO              1067
#define IDC_BTNDELETEELIMINAR           1068
#define IDC_LIST4                       1072
#define IDC_BTNMODESP                   1073
#define IDC_BTNDELETEESP                1074
#define IDC_LBPAQUETES                  1075
#define IDC_BTNLIMPIARPAQ               1076
#define IDC_BTNLIMPIARCLIENTE           1079
#define IDC_BTNLIMPIARMECANICO          1083
#define IDC_LBMECANICOCITA              1085
#define IDC_LBCITASREG                  1086
#define IDC_BTNESPBUSCAR                1089
#define IDC_RDSI                        1090
#define IDC_RDNO                        1091
#define IDC_BUTTON2                     1094
#define IDC_BTNSELMEC                   1094
#define IDC_BTNGUARDAR                  1094
#define IDC_BTNVERREPORTE               1094
#define IDC_BTNMODCITA                  1095
#define IDC_BTNELIMINARCITA             1096
#define IDC_NOMMECANICOCITA             1098
#define IDC_NOMBRECLIENTECITA           1099
#define IDC_CELULARCLCITA               1100
#define IDC_DIACITAS                    1101
#define IDC_CBHORACITA                  1105
#define IDC_MESCITA                     1106
#define IDC_MESCITAXMECANICO            1107
#define IDC_LBCITASXMEC                 1108
#define IDC_BTNCITAXMECANICO            1109
#define IDC_PAQUETECITAMEC              1111
#define IDC_MONTHCALENDAR1              1112
#define IDC_LBCITASXMES                 1113
#define IDC_CBCITASXPAQUETE             1114
#define IDC_BTNCITASXPAQUETE            1115
#define IDC_LBCITASXPAQUETE             1116
#define IDC_CKLUNES                     1117
#define IDC_CKMARTES                    1118
#define IDC_CKMIERCOLES                 1119
#define IDC_CKJUEVES                    1120
#define IDC_CKVIERNES                   1121
#define IDC_DTPCITA                     1122
#define IDC_LBCLIENTESR                 1123
#define IDC_USUARIONOMR                 1124
#define IDC_EDBAPMA                     1125
#define IDC_APCLIENTE2                  1125
#define ID_BTNVER                       1127
#define IDC_BTNREGMEC                   1128
#define IDC_LBREPMEC                    1129
#define IDC_BTNREPMEC                   1130
#define IDC_NOMDEUSUR                   1131
#define IDC_CBHORA                      1132
#define IDC_CBMINUTOS                   1133
#define IDC_BTNSELECCION                1134
#define IDC_BTNLIMPIARCITA              1135
#define IDC_CLIENTE                     1136
#define IDC_CLAVEDCITA                  1137
#define IDC_LUNESC                      1138
#define IDC_MARTESC                     1139
#define IDC_MIERCOLESC                  1140
#define IDC_JUEVESC                     1141
#define IDC_VIERNESC                    1142
#define IDC_FECHACITAACT                1147
#define IDC_TNMEDICO                    1148
#define IDC_CBCLAVCITA                  1149
#define IDC_LBCLAVCITA                  1149
#define IDC_FECHAREP                    1150
#define IDC_HORAREP                     1151
#define IDC_CITASI                      1152
#define IDC_CITANO                      1153
#define IDC_ESPREPORTE                  1154
#define IDC_NOMMECREP                   1155
#define IDC_NOMCLREP                    1156
#define IDC_CELREPORTE                  1157
#define IDC_MOTIVOCANCEL                1158
#define IDC_FOTOREPORTE                 1159
#define IDC_BTNELEGIRMES                1160
#define IDC_BTNSELREPORTE               1161
#define IDC_BTNCANCELREP                1162
#define IDC_BTNLIMPIARREPO              1163
#define IDC_CBMESREP                    1166
#define IDC_CBSEMREP                    1167
#define IDC_CBMESCITAXP                 1168
#define IDC_CBSEMXPAQ                   1169
#define IDC_LBPAQ                       1170
#define IDC_NOMDUSURU                   1171
#define IDC_LBCONSXNUM                  1172
#define IDC_BTNCONSULXNUM               1173
#define IDC_CBMESXMECANICO              1174
#define IDC_NUMXMECANICO                1176
#define IDC_EDIT1                       1178
#define IDC_NUMNOMXMEC                  1179
#define IDC_BUTTON1                     1180
#define IDC_BUSCARCITAXMESMEC           1180
#define IDC_BITMAPMEC                   1236
#define IDC_TNMECANICO                  1248
#define IDC_CLAVECITA                   1254
#define IDC_BTNCITASXMES                1260
#define IDC_CBNUMNOM                    1348
#define IDC_NUMNOMINACITA               1354
#define IDC_BTNREPORTE                  1360
#define IDC_EDBAPPA                     1454
#define IDC_BTNREGRESAR                 1460
#define IDC_APCLIENTE                   1554
#define IDC_NOMBREUUSUARIO              1560
#define ID_REGISTRODEMECANICOS_REPORTE  40001
#define ID_REGISTROPAQ                  40002
#define ID_SALIR                        40003
#define ID_CONSULTASDECITAS             40004
#define ID_REGISTRODECLIENTES           40005
#define ID_REGISTRODECITAS              40006
#define ID_REGISTRODEMECANICOS          40007
#define ID_CONSULTASDECITAS_PORMECANICO 40008
#define ID_CONSULTASDECITAS_PORSEMANA   40009
#define ID_CONSULTASDECITAS_PORPAQUETEDESERVICIO 40010
#define ID_CONSULTASDECITAS_MODIFICAR   40011
#define ID_CONSULTASDECITAS_REPORTEDECITAS 40012
#define ID_CONSULTASDECITAS_PORNUMERODECITAS 40013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40014
#define _APS_NEXT_CONTROL_VALUE         1181
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
